# Generated by Django 5.2.6 on 2025-09-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="thread_type",
            field=models.CharField(
                choices=[("DEBATE", "Debate"), ("AYUDA", "Petición de Ayuda")],
                default="DEBATE",
                max_length=10,
            ),
        ),
    ]
