# Generated by Django 5.2.6 on 2025-09-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_thread_thread_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEBATE", "Debatir"),
                    ("SOLUCION", "Ofrecer Solución"),
                    ("PROBLEMA", "Tengo el mismo problema"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
